# this is a copy of the original applicationSample.yml
# change the placeholder to the original value
# ask the developer for the key

spring:
  # database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garlands
    username: root
    password: masnico123

  # 404
  mvc:
    throw-exception-if-no-handler-found: true

  # social
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: yourClientId
            clientSecret: yourClientSecret
            redirectUri: path
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=name,email,picture.width(250).height(250)
jwt:
  key: 703273357638792F423F4528482B4D6250655368566D597133743677397A2443

webhook:
  discord:
    url: https://discord.com/api/webhooks/
    clientId: yourClientId
    token: secret-token

paypal:
  mode: paypalMode
  clientId: yourClientId
  clientSecret: yourSecretId